# Generated by Django 3.2.13 on 2023-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230927_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='expiration',
            field=models.DateTimeField(default=15000),
        ),
    ]
