# Generated by Django 3.2.13 on 2023-09-27 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_emailverification_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverification',
            name='user',
        ),
    ]
