# Generated by Django 3.2.13 on 2023-09-30 05:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20230930_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
